[package]
name = "Banana-Blueprint"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Archie Webster <https://github.com/artomweb>"]
license = "MIT"
description = "A template for creating A6 recipe cards."
repository = "https://github.com/artomweb/Banana-Blueprint"
keywords = ["recipe", "printable", "banana"]
categories = ["utility"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"